### ISSUE TITLE
Incorrect evaluation of terminal state

### ISSUE THREAD

**Issue by ishit** [zhangy111/gobblet#2]
Returns 'win' for these states:
![state1](https://user-images.githubusercontent.com/4801132/110587270-4b7b9f80-8128-11eb-982c-420206345ae9.png)
![state2](https://user-images.githubusercontent.com/4801132/110587286-4f0f2680-8128-11eb-9579-6c6372500d5e.png)
![state3](https://user-images.githubusercontent.com/4801132/110587291-50d8ea00-8128-11eb-9160-22d4d0adc6e4.png)

**Comment by zhangy111** [comment]
I updated board.py, can you try again please?

**Comment by ishit** [comment]
![screenshot](https://user-images.githubusercontent.com/4801132/110597353-4c66fe00-8135-11eb-96cd-2e82139696fb.png)
@zhangy111  This returns a win

**Comment by zhangy111** [comment]
Looked at the code again, not sure where the issue is...

**Comment by ishit** [comment]
It's this
https://github.com/zhangy111/gobblet/blob/bed9f917735b29e21c092c20d467da6e33bb30a1/score_jennifer.py#L206

**Comment by ishit** [comment]
The state of the board changes in a scoring function. I had my hair pulled for an hour.

**Comment by ishit** [comment]
It's this
https://github.com/zhangy111/gobblet/blob/87bde6bc8b9148e397b7096a826bb5a01d5cbf48/score_jennifer.py#L189

**Comment by chiennifer** [comment]
okay try now
